SELECT
T1.DEPARTMENT AS Department,
T1.EMPLOYEE AS Employee,
T1.SALARY AS Salary
FROM(
    SELECT
        D.NAME AS Department,
        E.NAME AS Employee,
        E.SALARY AS Salary,
        DENSE_RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) AS RNK
    FROM
        EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID) AS T1
    WHERE T1.RNK <= 3;